# Generated by Django 4.2.4 on 2023-08-24 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mohaffiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/MohaffizProfilePic/', verbose_name='الصورة الشخصية')),
                ('address', models.CharField(max_length=40, verbose_name='العنوان')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='رقم الجوال')),
                ('department', models.CharField(choices=[('خالد بن الوليد', 'خالد بن الوليد'), ('زيد بن حارثة', 'زيد بن حارثة'), ('معاذ بن جبل', 'معاذ بن جبل')], default='خالد بن الوليد', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
