# Generated by Django 4.2.4 on 2023-09-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0002_achievement_circle_honorroll_recitation_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='supervisor_teacher',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='mosque_name',
        ),
        migrations.AddField(
            model_name='circle',
            name='masjed_name',
            field=models.CharField(default='', max_length=255, verbose_name='اسم المسجد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circle',
            name='address',
            field=models.TextField(verbose_name='عنوان المسجد'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الحلقة'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='work_schedule',
            field=models.CharField(max_length=255, verbose_name='وقت تفعيل الحلقة'),
        ),
    ]
