# Generated by Django 4.2.4 on 2023-09-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0003_rename_supervisor_teacher_circle_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='monthly_attendance',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Monthly_absence',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد أيام الحضور'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(verbose_name='عنوان السكن'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='الإسم رباعي'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='teachers/', verbose_name='صورة المحفظ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='national_id',
            field=models.CharField(max_length=14, unique=True, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='personal_mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الجوال'),
        ),
    ]
