# Generated by Django 4.2.4 on 2023-09-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0004_remove_teacher_monthly_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='monthly_attendance',
        ),
        migrations.AddField(
            model_name='student',
            name='Monthly_absence',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد أيام الغياب'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Monthly_absence',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد أيام الغياب'),
        ),
    ]
