# Generated by Django 4.2.4 on 2023-09-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0005_remove_student_monthly_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='students',
        ),
        migrations.AddField(
            model_name='achievement',
            name='certificate_type',
            field=models.CharField(choices=[('شرعية', 'شرعية'), ('علمية', 'علمية')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(verbose_name='عنوان السكن'),
        ),
        migrations.AlterField(
            model_name='student',
            name='combined_tests',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الإختبارات المجتمعة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_hifz',
            field=models.CharField(max_length=255, verbose_name='الحفظ الحالي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_stage',
            field=models.CharField(max_length=255, verbose_name='المستوى الدراسي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='الإسم رباعي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_mobile',
            field=models.CharField(max_length=15, verbose_name='رقم جوال ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='students/', verbose_name='صورة الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=14, unique=True, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الجوال الشخصي (اختياري)'),
        ),
    ]
