# Generated by Django 4.2.4 on 2023-09-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0006_remove_achievement_image_remove_achievement_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='mohaffiz.teacher'),
        ),
    ]
