# Generated by Django 4.2.4 on 2023-09-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0010_student_user_teacher_user_alter_achievement_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='honorroll',
            name='circle',
        ),
        migrations.RemoveField(
            model_name='honorroll',
            name='student',
        ),
        migrations.RemoveField(
            model_name='honorroll',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='PatientDischargeDetails',
        ),
        migrations.RemoveField(
            model_name='recitation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='test',
            name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='national_id',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='national_id',
            new_name='id_number',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='assignedTeacherId',
        ),
        migrations.RemoveField(
            model_name='student',
            name='circle',
        ),
        migrations.RemoveField(
            model_name='student',
            name='combined_tests',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='mohaffiz.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='circle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='mohaffiz.circle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circle',
            name='masjed_name',
            field=models.CharField(max_length=100, verbose_name='اسم المسجد'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الحلقة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_hifz',
            field=models.CharField(max_length=100, verbose_name='الحفظ الحالي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_stage',
            field=models.CharField(max_length=100, verbose_name='المستوى الدراسي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='الإسم رباعي'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='الإسم رباعي'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='personal_mobile',
            field=models.CharField(default=1, max_length=15, verbose_name='رقم الجوال'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='HonorRoll',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Recitation',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
