# Generated by Django 4.2.4 on 2023-09-25 13:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0011_remove_achievement_teacher_delete_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_count', models.PositiveIntegerField(verbose_name='عدد الأجزاء')),
                ('initial_part_number', models.PositiveIntegerField(verbose_name='من بداية جزء')),
                ('final_part_number', models.PositiveIntegerField(verbose_name='إلى نهاية جزء')),
                ('test_date', models.DateField(default=datetime.datetime(2023, 9, 25, 16, 47, 18, 272879))),
                ('result', models.IntegerField(verbose_name='معدل الإختبار')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mohaffiz.student')),
            ],
        ),
    ]
