# Generated by Django 4.2.4 on 2023-09-25 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0012_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 16, 51, 21, 730654), verbose_name='تاريخ الإختبار'),
        ),
    ]
