# Generated by Django 4.2.4 on 2023-09-25 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0013_alter_test_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 20, 49, 41, 467040), verbose_name='تاريخ الإختبار'),
        ),
    ]
