# Generated by Django 4.2.4 on 2023-09-26 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0016_alter_student_teacher_alter_teacher_circle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='final_part_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], max_length=10, verbose_name='إلى نهاية جزء'),
        ),
        migrations.AlterField(
            model_name='test',
            name='initial_part_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], max_length=10, verbose_name='من بداية جزء'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 13, 13, 33, 53475), verbose_name='تاريخ الإختبار'),
        ),
    ]
