# Generated by Django 4.2.4 on 2023-09-26 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0017_alter_test_final_part_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 13, 20, 24, 914633), verbose_name='تاريخ الإختبار'),
        ),
    ]
