# Generated by Django 4.2.4 on 2023-09-26 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0022_alter_dailysaving_surah_alter_test_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreview',
            name='surah_or_part',
        ),
        migrations.AddField(
            model_name='dailyreview',
            name='surah',
            field=models.CharField(default=1, max_length=100, verbose_name='اختر السورة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyreview',
            name='end_verse',
            field=models.PositiveIntegerField(verbose_name='رقم آية النهاية'),
        ),
        migrations.AlterField(
            model_name='dailyreview',
            name='start_verse',
            field=models.PositiveIntegerField(verbose_name='رقم آية البداية'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 15, 21, 32, 869080), verbose_name='تاريخ الإختبار'),
        ),
    ]
