# Generated by Django 4.2.4 on 2023-09-26 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0023_remove_dailyreview_surah_or_part_dailyreview_surah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإختبار'),
        ),
    ]
