# Generated by Django 4.2.4 on 2023-09-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0025_alter_dailyreview_surah_alter_dailysaving_end_verse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysaving',
            old_name='start_verse',
            new_name='ayat_number',
        ),
        migrations.RenameField(
            model_name='dailysaving',
            old_name='end_verse',
            new_name='ayat_number2',
        ),
        migrations.RenameField(
            model_name='dailysaving',
            old_name='surah',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dailysaving',
            old_name='student',
            new_name='student_name',
        ),
    ]
