# Generated by Django 4.2.4 on 2023-09-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0026_rename_start_verse_dailysaving_ayat_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysaving',
            old_name='ayat_number2',
            new_name='end_verse',
        ),
        migrations.RenameField(
            model_name='dailysaving',
            old_name='ayat_number',
            new_name='start_verse',
        ),
        migrations.RenameField(
            model_name='dailysaving',
            old_name='student_name',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='dailysaving',
            old_name='name',
            new_name='surah',
        ),
    ]
