# Generated by Django 4.2.4 on 2023-09-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0027_rename_ayat_number2_dailysaving_end_verse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysaving',
            name='surah',
            field=models.CharField(max_length=100, verbose_name='اختر السورة'),
        ),
    ]
