# Generated by Django 4.2.4 on 2023-09-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0028_alter_dailysaving_surah'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysaving',
            old_name='start_verse',
            new_name='ayat_number',
        ),
        migrations.RenameField(
            model_name='dailysaving',
            old_name='end_verse',
            new_name='ayat_number2',
        ),
        migrations.RenameField(
            model_name='dailysaving',
            old_name='surah',
            new_name='name',
        ),
    ]
