# Generated by Django 4.2.4 on 2023-09-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0031_alter_dailysaving_ayat_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysaving',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
