# Generated by Django 4.2.4 on 2023-09-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaffiz', '0032_dailysaving_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreview',
            old_name='start_verse',
            new_name='ayat_number',
        ),
        migrations.RenameField(
            model_name='dailyreview',
            old_name='end_verse',
            new_name='ayat_number2',
        ),
        migrations.RemoveField(
            model_name='dailyreview',
            name='surah',
        ),
        migrations.AddField(
            model_name='dailyreview',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyreview',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='اختر السورة'),
            preserve_default=False,
        ),
    ]
